# Generated by Django 2.1.3 on 2019-03-28 05:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ws', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', tinymce.models.HTMLField()),
                ('monto', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('borrado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado')),
                ('financiacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Financiacion')),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidad')),
                ('municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
                ('organismo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organismo')),
            ],
        ),
        migrations.RemoveField(
            model_name='accion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='organismo',
        ),
        migrations.RemoveField(
            model_name='accion',
            name='tipo_financiacion',
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
    ]
