# Generated by Django 2.1.3 on 2019-03-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190328_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='id_ws',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='monto',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
