# Generated by Django 2.1.3 on 2019-03-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190328_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='organismo_id',
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicable'),
        ),
    ]
