# Generated by Django 2.1.3 on 2019-03-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190328_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='monto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
