# Generated by Django 2.1.3 on 2019-04-01 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190328_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('monto', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Comunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='medio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Comunicacion'),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='id_accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Acciones'),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Medio'),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Comunicacion'),
        ),
    ]
