# Generated by Django 2.1.3 on 2019-04-03 14:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190403_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='core.Localidad'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
