# Generated by Django 2.1.3 on 2019-04-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190411_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='importancia',
            field=models.IntegerField(choices=[(0, 'Indefinida'), (3, 'Leve'), (6, 'Intermedia'), (9, 'Prioritaria')], default=9),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='localidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='core.Localidad'),
        ),
    ]
